language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - eval "${MATRIX_EVAL}"
        - "sudo apt-get -qq update"
        - "sudo apt-get install -y libegl1-mesa-dev"
        - "sudo apt-get install -y libfreetype6-dev"
        - "sudo apt-get install -y libogg-dev"
        - "sudo apt-get install -y libvorbis-dev"
        - "sudo apt-get install -y libsdl2-dev"
        #- "sudo apt-get install -y libarchive-dev"
        - "sudo apt-get install -y zlib1g-dev --reinstall"
        - "sudo apt-get install -y libjpeg-dev --reinstall"
      install:
        #Libpng
        - LIBPNG_URL="http://download.sourceforge.net/libpng/libpng-1.6.24.tar.gz"
        - mkdir libpng && travis_retry wget --no-check-certificate --quiet -O - ${LIBPNG_URL} | tar --strip-components=1 -xz -C libpng
        - cd libpng
        - cmake .
        - LIBS="-lpthread ./configure --prefix=/usr --disable-static &&"
        - make
        - sudo make install
        - cd ..
        #SDL-2.0.9
        - SDL_URL="https://www.libsdl.org/release/SDL2-2.0.9.tar.gz"
        - mkdir sdl && travis_retry wget --no-check-certificate --quiet -O - ${SDL_URL} | tar --strip-components=1 -xz -C sdl
        - cd sdl
        - ./configure
        - make
        - sudo make install
        - cd ..
        #LibArchive
        - LA_URL="https://www.libarchive.org/downloads/libarchive-3.3.3.tar.gz"
        - mkdir la && travis_retry wget --no-check-certificate --quiet -O - ${LA_URL} | tar --strip-components=1 -xz -C la
        - cd la
        - ./configure
        - make
        - make check
        - sudo make install
        - cd ..
        
        
#    - os: osx 
#      osx_image: xcode9.3
#      addons:
#        homebrew:
#          update: true
#          packages:
#            - cmake
#            - freetype
#            - libvorbis
#            - sdl2
#            - libpng
#            - jpeg
#            - libarchive
#      before_script:
#        - brew link -f libarchive

before_install:
  - "git submodule update --init --recursive"

script:
  - "gcc --version"
  - "cmake ."
  - "make"
